"""boofuzz harness generator.

Given a driver path and its extracted IOCTL surface (from driverscope.ioctl),
emit a runnable boofuzz template that:
  - Opens the device (\\\\.\\<device_name>)
  - Iterates each IOCTL code
  - For METHOD_NEITHER codes, fuzzes the input buffer (LPVOID, SystemBuffer)
  - For METHOD_BUFFERED, fuzzes the input buffer up to a sane cap
  - For METHOD_IN_DIRECT / METHOD_OUT_DIRECT, fuzzes a MDL-backed buffer
  - Logs the crash-triggering input and stops the target if it crashes.

The generated file is standalone; the caller runs it with
`py -m boofuzz.tools ...` or just `python fuzz_<driver>.py` after installing
`pip install boofuzz`.

Notes:
  - This does NOT actually run the fuzzer. It generates the harness only.
  - You still need admin + the driver loaded to run the harness.
  - Output includes a --dry-run switch so the operator can inspect the
    payload plan without opening the device.
"""
from __future__ import annotations

import textwrap
from dataclasses import is_dataclass, asdict
from pathlib import Path
from typing import Any, Iterable, Optional


TEMPLATE = r'''"""Auto-generated boofuzz harness for {driver_filename}.
Generated by driverscope.fuzz_gen — do not commit this file.

USAGE:
  pip install boofuzz pywin32
  python {harness_name} --device \\.\{device_name} --list        # show plan
  python {harness_name} --device \\.\{device_name}               # fuzz
  python {harness_name} --device \\.\{device_name} --code 0x{first_code:x}   # single code

NOTES:
  - Requires admin.
  - The target driver must be loaded and the device symlink open-able.
  - Crash reports are written to boofuzz-results/ under CWD.
"""

import argparse
import ctypes
import os
import struct
import sys
from ctypes import wintypes

try:
    from boofuzz import Session, Target, SocketConnection, s_initialize, s_get, s_static, s_random
except ImportError:
    Session = None  # allow --dry-run without boofuzz installed

GENERIC_READ    = 0x80000000
GENERIC_WRITE   = 0x40000000
OPEN_EXISTING   = 3
FILE_ATTRIBUTE_NORMAL = 0x80
FILE_FLAG_OVERLAPPED = 0x40000000

CreateFileW = ctypes.windll.kernel32.CreateFileW
CreateFileW.argtypes = [wintypes.LPCWSTR, wintypes.DWORD, wintypes.DWORD,
                        ctypes.c_void_p, wintypes.DWORD, wintypes.DWORD, wintypes.HANDLE]
CreateFileW.restype = wintypes.HANDLE
DeviceIoControl = ctypes.windll.kernel32.DeviceIoControl
DeviceIoControl.argtypes = [wintypes.HANDLE, wintypes.DWORD,
                            ctypes.c_void_p, wintypes.DWORD,
                            ctypes.c_void_p, wintypes.DWORD,
                            ctypes.POINTER(wintypes.DWORD), ctypes.c_void_p]
DeviceIoControl.restype = wintypes.BOOL
CloseHandle = ctypes.windll.kernel32.CloseHandle
CloseHandle.argtypes = [wintypes.HANDLE]

INVALID_HANDLE_VALUE = wintypes.HANDLE(-1).value


# ── IOCTL plan (extracted from PE) ─────────────────────────────────────

IOCTL_PLAN = {ioctl_plan_repr}


# ── payload strategies ────────────────────────────────────────────────

def _payloads_for(method: int, in_max: int):
    """Yield a set of payloads sized/shaped for this IOCTL's method."""
    caps = [0, 1, 4, 8, 16, 64, 256, 512, 4096, 65536]
    if in_max and in_max > 0:
        caps.append(in_max)
        caps.append(in_max + 4)
        caps.append(in_max * 2)
    # Also try some famously bad values.
    yield b""
    for c in sorted(set(caps)):
        if c == 0:
            continue
        yield b"A" * c
        yield b"\x00" * c
        yield b"\xff" * c
        yield struct.pack("<Q", 0xFFFFFFFFFFFFFFFF) + b"A" * max(0, c - 8)
        yield struct.pack("<Q", 0x4141414141414141) + b"A" * max(0, c - 8)
        yield os.urandom(c)


# ── driver interaction ────────────────────────────────────────────────

def open_device(device: str) -> int:
    h = CreateFileW(device, GENERIC_READ | GENERIC_WRITE, 0, None, OPEN_EXISTING,
                    FILE_ATTRIBUTE_NORMAL, None)
    if h == INVALID_HANDLE_VALUE:
        err = ctypes.GetLastError()
        raise SystemExit(f"CreateFileW({{device}}) failed, GLE={{err}}")
    return h


def send_ioctl(handle: int, code: int, payload: bytes, out_len: int = 4096) -> tuple[bool, int, bytes]:
    inbuf = (ctypes.c_ubyte * len(payload)).from_buffer_copy(payload) if payload else None
    outbuf = (ctypes.c_ubyte * out_len)()
    returned = wintypes.DWORD(0)
    ok = DeviceIoControl(
        handle, code,
        inbuf, len(payload),
        outbuf, out_len,
        ctypes.byref(returned), None,
    )
    return bool(ok), returned.value, bytes(outbuf[:returned.value])


def crash_probe(device: str) -> bool:
    """Try to open the device; if that fails after crashing, the driver died."""
    h = CreateFileW(device, GENERIC_READ | GENERIC_WRITE, 0, None, OPEN_EXISTING,
                    FILE_ATTRIBUTE_NORMAL, None)
    if h == INVALID_HANDLE_VALUE:
        return False
    CloseHandle(h)
    return True


def fuzz_one(handle: int, code: int, plan: dict, verbose: bool, dry_run: bool):
    method = plan.get("method", 3)
    method_name = plan.get("method_name", "?")
    in_max = plan.get("in_max", 0)
    tag = f"code=0x{{code:08x}} method={{method_name}} in_max={{in_max}}"
    for i, payload in enumerate(_payloads_for(method, in_max)):
        if verbose or dry_run:
            print(f"  {{tag}}  #{{i}}  len={{len(payload)}}")
        if dry_run:
            continue
        try:
            send_ioctl(handle, code, payload)
        except Exception as e:
            print(f"    exception: {{e}}")


def main():
    ap = argparse.ArgumentParser(description="boofuzz harness for {driver_filename}")
    ap.add_argument("--device", required=True, help=r"Symlink path, e.g. \\.\{device_name}")
    ap.add_argument("--list", action="store_true", help="Print the IOCTL plan and exit")
    ap.add_argument("--code", type=lambda s: int(s, 0), default=None,
                    help="Fuzz only a single IOCTL code (hex)")
    ap.add_argument("--dry-run", action="store_true",
                    help="Enumerate payloads without opening the device")
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()

    if args.list:
        for entry in IOCTL_PLAN:
            print(f"  code=0x{{entry['code']:08x}}  method={{entry['method_name']}}  "
                  f"access={{entry['access_name']}}  flags={{','.join(entry.get('danger_flags', [])) or '-'}}")
        return

    handle = None
    if not args.dry_run:
        handle = open_device(args.device)
        print(f"[fuzz] opened {{args.device}} handle={{handle}}")

    try:
        for entry in IOCTL_PLAN:
            if args.code is not None and entry["code"] != args.code:
                continue
            fuzz_one(handle or 0, entry["code"], entry, args.verbose, args.dry_run)
    finally:
        if handle:
            CloseHandle(handle)


if __name__ == "__main__":
    main()
'''


def _fmt_int(x: Any) -> int:
    if isinstance(x, str) and x.lower().startswith("0x"):
        return int(x, 16)
    try:
        return int(x)
    except Exception:
        return 0


def _ioctl_to_dict(io: Any) -> dict:
    if isinstance(io, dict):
        d = dict(io)
    elif is_dataclass(io):
        d = asdict(io)
    else:
        d = {k: getattr(io, k, None) for k in ("code", "method", "method_name", "access",
                                                "access_name", "in_max", "danger_flags",
                                                "primitive_classes")}
    code_val = d.get("code")
    if isinstance(code_val, str):
        d["code"] = _fmt_int(code_val)
    d.setdefault("in_max", 0)
    d.setdefault("method", 3)
    d.setdefault("method_name", "METHOD_NEITHER")
    d.setdefault("access_name", "FILE_ANY_ACCESS")
    d.setdefault("danger_flags", [])
    d.setdefault("primitive_classes", [])
    return d


def generate(driver_path: str | Path,
             surface: Any,
             out_path: Optional[str | Path] = None,
             only_flagged: bool = True,
             device_name_override: str = "") -> str:
    """Return the harness source, and write to out_path if given."""
    codes = list(getattr(surface, "ioctls", []) or [])
    if only_flagged:
        codes = [c for c in codes
                 if (getattr(c, "primitive_classes", None) or getattr(c, "danger_flags", None))]
    if not codes:
        # If nothing "interesting", fall back to all codes
        codes = list(getattr(surface, "ioctls", []) or [])

    ioctl_plan = [_ioctl_to_dict(io) for io in codes]

    device_name = device_name_override or (
        getattr(surface, "device_name", "") or Path(driver_path).stem
    )
    device_name = device_name.strip("\\").split("\\")[-1]
    driver_filename = Path(driver_path).name
    first_code = ioctl_plan[0]["code"] if ioctl_plan else 0
    harness_name = f"fuzz_{Path(driver_path).stem}.py"

    body = TEMPLATE.format(
        driver_filename=driver_filename,
        device_name=device_name,
        harness_name=harness_name,
        ioctl_plan_repr=repr(ioctl_plan),
        first_code=first_code,
    )

    if out_path:
        Path(out_path).write_text(body, encoding="utf-8")
    return body


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(description="Emit a boofuzz harness for a single driver")
    ap.add_argument("driver", help="Path to a .sys file")
    ap.add_argument("--out", type=str, default=None,
                    help="Output .py path (defaults to fuzz_<driver>.py in CWD)")
    ap.add_argument("--all", action="store_true",
                    help="Include all IOCTL codes, not just those with primitive/danger flags")
    ap.add_argument("--device", type=str, default="",
                    help="Override the device name inferred from the driver")
    args = ap.parse_args()

    try:
        from driverscope.ioctl import extract_ioctl_surface
    except Exception as e:
        raise SystemExit(f"[fuzz] cannot import driverscope.ioctl: {e}")

    surface = extract_ioctl_surface(args.driver)
    out = args.out or f"fuzz_{Path(args.driver).stem}.py"
    generate(args.driver, surface, out_path=out, only_flagged=not args.all,
             device_name_override=args.device)
    print(f"[fuzz] wrote {out}")
